version:  '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15673:15672
  xxljob:
    image: docker.io/xuxueli/xxl-job-admin:2.1.0
    restart: always
    container_name: xxljob
    ports:
      - 8001:8080
    depends_on:
      - db
    volumes:
      - /home/middleware/xxljob/applogs:/data/applogs
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  registry:
    image: tiny3/registry
    ports:
      - "8761:8761"
  config:
    image: tiny3/config
    ports:
      - "8888:8888"
  monitor:
    image: tiny3/monitor
    ports:
      - "8040:8040"
  gateway:
    image: tiny3/gateway
    ports:
      - "8060:8060"
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  auth-service:
    image: tiny3/auth-service
    ports:
      - "5000:5000"